services:
  camagru:
    build:
      context: .
      dockerfile_inline: |
        FROM php:8.2-fpm-alpine
        # Install dependencies for PostgreSQL and GD Graphics Library
        RUN apk add --no-cache libpq-dev libpng-dev libjpeg-turbo-dev freetype-dev \
            && docker-php-ext-configure gd --with-freetype --with-jpeg \
            && docker-php-ext-install pdo_pgsql gd
    container_name: app
    volumes:
      - ./src:/var/www/html
    networks:
      - camagru_net
    links:
      - database:database
    command: >
      sh -c "mkdir -p /var/www/html/uploads/overlays && chmod -R 777 /var/www/html/uploads && php-fpm"  
  
  webserver:
    image: nginx:alpine
    container_name: web
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/ssl:/etc/nginx/ssl
    depends_on:
      - camagru
      - database
    networks:
      - camagru_net

  database:
    image: postgres:alpine
    container_name: db
    hostname: database
    environment:
      POSTGRES_USER: camagru_user
      POSTGRES_PASSWORD: camagru_pass
      POSTGRES_DB: camagru_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql
      - ./src/config/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - camagru_net

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8081:8080"
    depends_on:
      - database
    networks:
      - camagru_net

networks:
  camagru_net:
    driver: bridge

volumes:
  pg_data:
